# Assignment 5, Question 6: Data Transformation

**Points: 20**

Transform and engineer features from the clinical trial dataset.

## Setup

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import utilities
from q3_data_utils import load_data, clean_data, transform_types, create_bins, fill_missing

df = load_data('data/clinical_trial_raw.csv')
print(f"Loaded {len(df)} patients")

# Prewritten visualization functions for transformation analysis
def plot_distribution(series, title, figsize=(10, 6)):
    """
    Create a histogram of a numeric series.
    
    Args:
        series: pandas Series with numeric data
        title: Chart title
        figsize: Figure size tuple
    """
    plt.figure(figsize=figsize)
    series.hist(bins=30)
    plt.title(title)
    plt.xlabel('Value')
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

def plot_value_counts(series, title, figsize=(10, 6)):
    """
    Create a bar chart of value counts.
    
    Args:
        series: pandas Series with value counts
        title: Chart title
        figsize: Figure size tuple
    """
    plt.figure(figsize=figsize)
    series.plot(kind='bar')
    plt.title(title)
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.show()

Loaded 10000 patients

## Part 1: Type Conversions (5 points)

1. Convert 'enrollment_date' to datetime using the `transform_types()` utility
2. Convert categorical columns ('site', 'intervention_group', 'sex') to category dtype
3. Ensure all numeric columns are proper numeric types
4. Display the updated dtypes

In [13]:
# TODO: Type conversions
# 1. Use transform_types() to convert enrollment_date to datetime
# 2. Convert categorical columns ('site', 'intervention_group', 'sex') to category dtype
# 3. Ensure all numeric columns are proper numeric types
# 4. Display the updated dtypes using df.dtypes

# Converting enrollment_date and categorical columns
df_copy = df.copy()
type_map = {
    'enrollment_date' : 'datetime',
    'site' : 'category', 
    'intervention_group': 'category',
    'sex': 'category'
}
df_copy = transform_types(df_copy, type_map)

# Ensure all numeric columns are proper numeric types 
numeric_cols = df_copy.select_dtypes(include='number').columns
print('Numeric columns:', numeric_cols)
print(df_copy.dtypes)

Numeric columns: Index(['age', 'bmi', 'systolic_bp', 'diastolic_bp', 'cholesterol_total',
       'cholesterol_hdl', 'cholesterol_ldl', 'glucose_fasting',
       'follow_up_months', 'adverse_events', 'adherence_pct'],
      dtype='object')
patient_id                    object
age                            int64
sex                         category
bmi                          float64
enrollment_date       datetime64[ns]
systolic_bp                  float64
diastolic_bp                 float64
cholesterol_total            float64
cholesterol_hdl              float64
cholesterol_ldl              float64
glucose_fasting              float64
site                        category
intervention_group          category
follow_up_months               int64
adverse_events                 int64
outcome_cvd                   object
adherence_pct                float64
dropout                       object
dtype: object

## Part 2: Feature Engineering (8 points)

Create these new calculated columns:

1. `cholesterol_ratio` = cholesterol_ldl / cholesterol_hdl
2. `bp_category` = categorize systolic BP:
   - 'Normal': < 120
   - 'Elevated': 120-129
   - 'High': >= 130
3. `age_group` using `create_bins()` utility:
   - Bins: [0, 40, 55, 70, 100]
   - Labels: ['<40', '40-54', '55-69', '70+']
4. `bmi_category` using standard BMI categories:
   - Underweight: <18.5
   - Normal: 18.5-24.9
   - Overweight: 25-29.9
   - Obese: >=30

In [14]:
# TODO: Calculate cholesterol ratio

df_copy['cholesterol_ratio'] = df_copy['cholesterol_ldl'] / df_copy['cholesterol_hdl']
df_copy

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,glucose_fasting,site,intervention_group,follow_up_months,adverse_events,outcome_cvd,adherence_pct,dropout,cholesterol_ratio
0,P00001,80,F,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,118.0,site b,Control,20,0,No,24.0,No,0.745455
1,P00002,80,Female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,79.0,Site A,CONTROL,24,0,No,77.0,No,1.844828
2,P00003,82,Female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,77.0,SITE C,treatment b,2,0,Yes,70.0,No,1.464286
3,P00004,95,Female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,115.0,Site D,treatment b,17,0,No,62.0,No,1.857143
4,P00005,95,M,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,113.0,site e,Treatmen A,9,0,yes,NaN,Yes,0.961538
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,Male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,97.0,site c,TREATMENT B,21,0,No,20.0,No,1.703704
9996,P09997,100,Female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,102.0,Site C,control,11,0,No,57.0,No,1.250000
9997,P09998,78,F,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,114.0,Site C,treatment a,2,1,No,77.0,No,1.028986
9998,P09999,86,F,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,126.0,SITE A,CONTROL,16,0,no,63.0,No,3.131579
9999,P10000,67,Female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,128.0,Site A,TREATMENT A,22,0,Yes,48.0,No,2.294118

In [17]:
# TODO: Categorize blood pressure

df_copy['bp_category'] = np.where(
    df_copy['systolic_bp'] < 120, 'Normal',
    np.where(df_copy['systolic_bp'] <=129, 'Elevated', 'High')
)
df_copy

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,glucose_fasting,site,intervention_group,follow_up_months,adverse_events,outcome_cvd,adherence_pct,dropout,cholesterol_ratio,bp_category
0,P00001,80,F,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,118.0,site b,Control,20,0,No,24.0,No,0.745455,Elevated
1,P00002,80,Female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,79.0,Site A,CONTROL,24,0,No,77.0,No,1.844828,High
2,P00003,82,Female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,77.0,SITE C,treatment b,2,0,Yes,70.0,No,1.464286,Elevated
3,P00004,95,Female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,115.0,Site D,treatment b,17,0,No,62.0,No,1.857143,Normal
4,P00005,95,M,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,113.0,site e,Treatmen A,9,0,yes,NaN,Yes,0.961538,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,Male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,97.0,site c,TREATMENT B,21,0,No,20.0,No,1.703704,Elevated
9996,P09997,100,Female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,102.0,Site C,control,11,0,No,57.0,No,1.250000,Elevated
9997,P09998,78,F,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,114.0,Site C,treatment a,2,1,No,77.0,No,1.028986,Normal
9998,P09999,86,F,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,126.0,SITE A,CONTROL,16,0,no,63.0,No,3.131579,High
9999,P10000,67,Female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,128.0,Site A,TREATMENT A,22,0,Yes,48.0,No,2.294118,High

**Note:** The `create_bins()` function has an optional `new_column` parameter. If you don't specify it, the new column will be named `{original_column}_binned`. You can use `new_column='age_group'` to give it a custom name.

In [27]:
# TODO: Create age groups
def create_bins(series, bins, labels):
    return pd.cut(series, bins=bins, labels=labels, right=False)

df_copy['age_group'] = create_bins(
    df_copy['age'],
    bins = [0, 40, 55, 70, 100],
    labels = ['<40', '40-54', '55-69', '70+']
)
df_copy

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,...,site,intervention_group,follow_up_months,adverse_events,outcome_cvd,adherence_pct,dropout,cholesterol_ratio,bp_category,age_group
0,P00001,80,F,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,...,site b,Control,20,0,No,24.0,No,0.745455,Elevated,70+
1,P00002,80,Female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,...,Site A,CONTROL,24,0,No,77.0,No,1.844828,High,70+
2,P00003,82,Female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,...,SITE C,treatment b,2,0,Yes,70.0,No,1.464286,Elevated,70+
3,P00004,95,Female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,...,Site D,treatment b,17,0,No,62.0,No,1.857143,Normal,70+
4,P00005,95,M,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,...,site e,Treatmen A,9,0,yes,NaN,Yes,0.961538,Normal,70+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,Male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,...,site c,TREATMENT B,21,0,No,20.0,No,1.703704,Elevated,70+
9996,P09997,100,Female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,...,Site C,control,11,0,No,57.0,No,1.250000,Elevated,NaN
9997,P09998,78,F,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,...,Site C,treatment a,2,1,No,77.0,No,1.028986,Normal,70+
9998,P09999,86,F,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,...,SITE A,CONTROL,16,0,no,63.0,No,3.131579,High,70+
9999,P10000,67,Female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,...,Site A,TREATMENT A,22,0,Yes,48.0,No,2.294118,High,55-69

In [29]:
# TODO: Create BMI categories
df_copy['bmi_category'] = np.where(
    df_copy['bmi'] < 18.5, 'Underweight',
    np.where(df_copy['bmi'] <=24.9, 'Normal',
    np.where(df_copy['bmi'] <=29.9, 'Overweight', 'Obese'))
)
df_copy

,patient_id,age,sex,bmi,enrollment_date,systolic_bp,diastolic_bp,cholesterol_total,cholesterol_hdl,cholesterol_ldl,...,intervention_group,follow_up_months,adverse_events,outcome_cvd,adherence_pct,dropout,cholesterol_ratio,bp_category,age_group,bmi_category
0,P00001,80,F,29.3,2022-05-01,123.0,80.0,120.0,55.0,41.0,...,Control,20,0,No,24.0,No,0.745455,Elevated,70+,Overweight
1,P00002,80,Female,NaN,2022-01-06,139.0,81.0,206.0,58.0,107.0,...,CONTROL,24,0,No,77.0,No,1.844828,High,70+,Obese
2,P00003,82,Female,-1.0,2023-11-04,123.0,86.0,172.0,56.0,82.0,...,treatment b,2,0,Yes,70.0,No,1.464286,Elevated,70+,Underweight
3,P00004,95,Female,25.4,2022-08-15,116.0,77.0,200.0,56.0,104.0,...,treatment b,17,0,No,62.0,No,1.857143,Normal,70+,Overweight
4,P00005,95,M,NaN,2023-04-17,97.0,71.0,185.0,78.0,75.0,...,Treatmen A,9,0,yes,NaN,Yes,0.961538,Normal,70+,Obese
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,P09996,72,Male,23.2,2022-04-11,122.0,73.0,182.0,54.0,92.0,...,TREATMENT B,21,0,No,20.0,No,1.703704,Elevated,70+,Normal
9996,P09997,100,Female,28.9,2023-02-10,124.0,78.0,157.0,56.0,70.0,...,control,11,0,No,57.0,No,1.250000,Elevated,NaN,Overweight
9997,P09998,78,F,23.8,2023-11-05,110.0,63.0,154.0,69.0,71.0,...,treatment a,2,1,No,77.0,No,1.028986,Normal,70+,Normal
9998,P09999,86,F,27.0,2022-08-27,139.0,98.0,196.0,38.0,119.0,...,CONTROL,16,0,no,63.0,No,3.131579,High,70+,Overweight
9999,P10000,67,Female,29.4,NaT,134.0,83.0,197.0,51.0,117.0,...,TREATMENT A,22,0,Yes,48.0,No,2.294118,High,55-69,Overweight

## Part 3: String Cleaning (2 points)

If there are any string columns that need cleaning:
1. Convert to lowercase
2. Strip whitespace
3. Replace any placeholder values

In [31]:
# TODO: String cleaning
placeholders = ['unknown', 'n/a', 'na', 'missing']

for col in df_copy.select_dtypes(include = 'object').columns:
    df_copy[col] = df_copy[col].str.lower()
    df_copy[col] = df_copy[col].str.strip
    df_copy[col] = df_copy[col].replace(placeholders, pd.NA)

## Part 4: One-Hot Encoding (5 points)

Create dummy variables for categorical columns:
1. One-hot encode 'intervention_group' using `pd.get_dummies()`
2. One-hot encode 'site'
3. Drop the original categorical columns
4. Show the new shape and column names

In [32]:
# TODO: One-hot encoding
dummies_intervention_group = pd.get_dummies(df_copy['intervention_group'], prefix = 'intervention')
dummies_site = pd.get_dummies(df_copy['site'], prefix = 'site')
df_copy = pd.concat([df_copy, dummies_intervention_group, dummies_site], axis=1)
df_copy = df_copy.drop(['intervention_group', 'site'], axis=1)
print('New Shape:', df_copy.shape)
print('Column Names:', df_copy.columns.tolist())

New Shape: (10000, 80)
Column Names: ['patient_id', 'age', 'sex', 'bmi', 'enrollment_date', 'systolic_bp', 'diastolic_bp', 'cholesterol_total', 'cholesterol_hdl', 'cholesterol_ldl', 'glucose_fasting', 'follow_up_months', 'adverse_events', 'outcome_cvd', 'adherence_pct', 'dropout', 'cholesterol_ratio', 'bp_category', 'age_group', 'bmi_category', 'intervention_  CONTROL  ', 'intervention_  Contrl  ', 'intervention_  Control  ', 'intervention_  TREATMENT A  ', 'intervention_  TREATMENT B  ', 'intervention_  Treatmen A  ', 'intervention_  Treatment  B  ', 'intervention_  Treatment A  ', 'intervention_  Treatment B  ', 'intervention_  TreatmentA  ', 'intervention_  control  ', 'intervention_  treatment a  ', 'intervention_  treatment b  ', 'intervention_CONTROL', 'intervention_Contrl', 'intervention_Control', 'intervention_TREATMENT A', 'intervention_TREATMENT B', 'intervention_Treatmen A', 'intervention_Treatment  B', 'intervention_Treatment A', 'intervention_Treatment B', 'intervention_TreatmentA', 'intervention_control', 'intervention_treatment a', 'intervention_treatment b', 'site_  SITE A  ', 'site_  SITE B  ', 'site_  SITE C  ', 'site_  SITE D  ', 'site_  SITE E  ', 'site_  Site  A  ', 'site_  Site A  ', 'site_  Site B  ', 'site_  Site C  ', 'site_  Site D  ', 'site_  Site E  ', 'site_  Site_D  ', 'site_  site a  ', 'site_  site b  ', 'site_  site c  ', 'site_  site d  ', 'site_  site e  ', 'site_SITE A', 'site_SITE B', 'site_SITE C', 'site_SITE D', 'site_SITE E', 'site_Site  A', 'site_Site A', 'site_Site B', 'site_Site C', 'site_Site D', 'site_Site E', 'site_Site_D', 'site_site a', 'site_site b', 'site_site c', 'site_site d', 'site_site e']

## Part 5: Save Transformed Data

Save the fully transformed dataset to `output/q6_transformed_data.csv`

In [33]:
# TODO: Save transformed data
# df_transformed.to_csv('output/q6_transformed_data.csv', index=False)

df_copy.to_csv('output/q6_transformed_data.csv', index = False)